version: '3'

services:
    web-app:
        # Use the image built from the Dockerfile in the current directory
        image: node:latest
        # Read environment variables from the .env file
        env_file:
            - .env
        # Specify the working directory inside the container
        working_dir: /app
        # Mount the current directory into the container for live code editing
        volumes:
            - .:/app
            - $SHARED_PATH:/app/shared
        # Expose the development server port (if needed)
        ports:
            - '5173:5173'
        # Install and run the development server using Yarn
        command:
            - sh
            - -c
            - |
                node tsconfig.merged.cjs
                if [ "$$SHARED_LINK" = "true" ]; then
                    cd /app/shared
                    yarn install
                    yarn build
                    yarn link
                    cd /app
                    yarn install
                    yarn link '@sanctuaryteam/shared'
                else
                    cd /app
                    yarn install
                fi
                yarn dev --host
