name: Build and Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SANCTUARYTEAM_AUTH_TOKEN: ${{ secrets.SANCTUARYTEAM_AUTH_TOKEN }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Set up .env
      run: echo "SANCTUARYTEAM_AUTH_TOKEN=${{ secrets.SANCTUARYTEAM_AUTH_TOKEN }}" >> .env | cp .env.example .env

    - name: Install TypeScript and Yarn
      run: |
        npm install -g typescript yarn
        
    - name: Get Yarn cache directory path
      id: yarn-cache
      run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: TypeScript build check
      run: yarn tsc

    - name: Run unit tests
      run: yarn test:unit
