name: Build and Test in Docker

on:
  push:
    branches:
      - main
      - develop
      - Task/add-actions
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TypeScript
      run: npm install -g typescript

    - name: Set up .env
      run: cp .env.example .env

    - name: Build and start the Docker containers
      run: docker-compose up -d

    - name: TypeScript build check
      run: docker-compose run web-app yarn tsc

    # Uncomment the following lines to enable unit tests
    #- name: Run unit tests inside Docker
    #  run: docker-compose run web-app yarn test:unit
